### ISSUE TITLE
Automate Package Installation for Missing Dependencies

### ISSUE THREAD

**Issue by Jai0401** [mem0ai/mem0#1768]
### Description:
Currently, missing dependencies require users to manually install packages, leading to potential errors. I propose adding functionality to automate this process.

### Proposed Solution:
Implement a mechanism to automatically prompt users to install missing packages. If they agree, the required package will be installed using `pip`.

#### Current Implementation:
```python
try:
    from ollama import Client
except ImportError:
    raise ImportError(
        "Ollama requires extra dependencies. Install with `pip install ollama`"
    ) from None

```
#### Proposed Implementation:
```python
import subprocess
import sys

try:
    from ollama import Client
except ImportError:
    user_agree = input("The 'ollama' library is required. Install it now? [y/N]: ")
    if user_agree.lower() == 'y':
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "ollama"])
            from ollama import Client
        except subprocess.CalledProcessError:
            print("Failed to install 'ollama'. Please install it manually.")
            sys.exit(1)
    else:
        raise ImportError("The required 'ollama' library is not installed.")
```

### Motivation, pitch

- **Enhanced User Experience**: Automates the installation of the packages.
- **Reduces Setup Issues**: Helps prevent errors related to missing dependencies.

## Tasks (Files to be Changed):

- [x] `mem0/configs/vector_stores/chroma.py`
- [x] `mem0/embeddings/ollama.py`
- [x] `mem0/llms/aws_bedrock.py`
- [x] `mem0/llms/groq.py`
- [x] `mem0/llms/litellm.py`
- [x] `mem0/llms/ollama.py`
- [x] `mem0/llms/together.py`
- [x] `mem0/vector_stores/chroma.py`
- [x] `mem0/proxy/main.py`
- [x] `mem0/vector_stores/pgvector.py`
- [ ] `embedchain/embedchain/embedder/ollama.py`
- [ ] `embedchain/embedchain/llm/base.py`
- [ ] `embedchain/embedchain/llm/google.py`
- [ ] `embedchain/embedchain/llm/groq.py`
- [ ] `embedchain/embedchain/llm/nvidia.py`
- [ ] `embedchain/embedchain/llm/ollama.py`
- [ ] `embedchain/embedchain/loaders/audio.py`
- [ ] `embedchain/embedchain/loaders/beehiiv.py`
- [ ] `embedchain/embedchain/loaders/docs_site_loader.py`
- [ ] `embedchain/embedchain/loaders/docx_file.py`
- [ ] `embedchain/embedchain/loaders/dropbox.py`
- [ ] `embedchain/embedchain/loaders/excel_file.py`
- [ ] `embedchain/embedchain/loaders/github.py`
- [ ] `embedchain/embedchain/loaders/gmail.py`
- [ ] `embedchain/embedchain/loaders/google_drive.py`
- [ ] `embedchain/embedchain/loaders/rss_feed.py`
- [ ] `embedchain/embedchain/loaders/sitemap.py`
- [ ] `embedchain/embedchain/loaders/slack.py`
- [ ] `embedchain/embedchain/loaders/substack.py`
- [ ] `embedchain/embedchain/loaders/unstructured_file.py`
- [ ] `embedchain/embedchain/loaders/web_page.py`
- [ ] `embedchain/embedchain/loaders/xml.py`
- [ ] `embedchain/embedchain/loaders/youtube_channel.py`
- [ ] `embedchain/embedchain/loaders/youtube_video.py`
- [ ] `embedchain/embedchain/vectordb/elasticsearch.py`
- [ ] `embedchain/embedchain/vectordb/opensearch.py`
- [ ] `embedchain/embedchain/vectordb/pinecone.py`
- [ ] `embedchain/embedchain/vectordb/qdrant.py`
- [ ] `embedchain/embedchain/vectordb/weaviate.py`
- [ ] `embedchain/embedchain/vectordb/zilliz.py`

**Comment by NavyaAlapati13** [comment]
Can you assign me this issue @Dev-Khant ? I am willing to work on it.

**Comment by Dev-Khant** [comment]
@NavyaAlapati13 Please feel free to work on it. Thanks.

**Comment by Jai0401** [comment]
Hi @Dev-Khant , I was already working on this issue and was waiting for the maintainers' approval before proceeding. Could I continue with the implementation? Thank you!

**Comment by Dev-Khant** [comment]
Hey @Jai0401 Sure, you can work on this. And please it is advisible to inform prior or mention in description that you are awaiting maintainer approval. Feel free to work on this. Looking forward for a PR!

@NavyaAlapati13 Sorry I'll have to unassign this issue from you as the author is already working on it. Feel free to work on other issues. Thanks!

**Comment by Jai0401** [comment]
Got it, @Dev-Khant! I'll make sure to mention it next time. Thanks for the guidance!

**Comment by Jai0401** [comment]
@Dev-Khant Could you please review these sample changes in pr #1780 ? I’ll proceed based on your feedback.

**Comment by deshraj** [comment]
Sorry, I should have communicated it earlier but we don't want to support this feature since it can cause issues in user's python environment without them being aware of it.

Will close this issue now. Thanks!
